### ISSUE TITLE
ValueError: cannot reshape array of size 150 into shape (1,300)

### ISSUE THREAD

**Issue by sachinsourav** [BehroozMansouri/TangentCFT#14]
Please help...

Traceback (most recent call last):
  File "tangent_cft_front_end.py", line 92, in <module>
    main()
  File "tangent_cft_front_end.py", line 69, in main
    retrieval_result = system.retrieval(dictionary_formula_tuples_collection,
  File "/TangentCFT-master/tangent_cft_back_end.py", line 68, in retrieval
    tensor_values, index_formula_id = self.module.index_collection_to_tensors(dictionary_formula_tuples_collection)
  File "/TangentCFT-master/tangent_cft_module.py", line 46, in index_collection_to_tensors
    xx = xx.reshape(1, 300)
ValueError: cannot reshape array of size 150 into shape (1,300)

Thank you

**Comment by BehroozMansouri** [comment]
This error is showing that instead of the vector size of 300, you have used a vector size of 150. If you run the original code this should not happen. Perhaps this happens after modification on the code, CFT original vector size is 300
