### ISSUE TITLE
RuntimeError: you must first build vocabulary before training the model

### ISSUE THREAD

**Issue by sachinsourav** [BehroozMansouri/TangentCFT#15]
please help....

encoding train data...
training the fast text model...
Setting Configuration
Training the model
Traceback (most recent call last):
  File "/a/Tangent/TangentCFT-master/tangent_cft_front_end.py", line 92, in <module>
    main()
  File "/a/Tangent/TangentCFT-master/tangent_cft_front_end.py", line 61, in main
    dictionary_formula_tuples_collection = system.train_model(
  File "/a/Tangent/TangentCFT-master/tangent_cft_back_end.py", line 39, in train_model
    self.module.train_model(self.config, list(dictionary_formula_tuples_collection.values()))
  File "/a/Tangent/TangentCFT-master/tangent_cft_module.py", line 30, in train_model
    self.model.train(configuration, lst_lst_encoded_tuples)
  File "/a/Tangent/TangentCFT-master/tangent_cft_model.py", line 37, in train
    self.model = FastText(fast_text_train_data, vector_size=size, window=window, sg=sg, hs=hs,
  File "/home/sachin/miniconda3/envs/my_env/lib/python3.10/site-packages/gensim/models/fasttext.py", line 435, in __init__
    super(FastText, self).__init__(
  File "/home/sachin/miniconda3/envs/my_env/lib/python3.10/site-packages/gensim/models/word2vec.py", line 427, in __init__
    self.train(
  File "/home/sachin/miniconda3/envs/my_env/lib/python3.10/site-packages/gensim/models/word2vec.py", line 1042, in train
    self._check_training_sanity(epochs=epochs, total_examples=total_examples, total_words=total_words)
  File "/home/sachin/miniconda3/envs/my_env/lib/python3.10/site-packages/gensim/models/word2vec.py", line 1540, in _check_training_sanity
    raise RuntimeError("you must first build vocabulary before training the model")
RuntimeError: you must first build vocabulary before training the model

i think model.build_vocab(, update=True)
is missing or something please help

**Comment by BehroozMansouri** [comment]
Please debug the code and the file paths you pass to the encoded. This error is caused as no vocabulary is passed to fastText model. In line 37 of tangent_cft_back_end.py check if you are not passing an empty dictionary to your model.

**Comment by sachinsourav** [comment]
i printed after training the fast text mode..
print(list(dictionary_formula_tuples_collection.values()))
it give empty []

-------------------------------------
encoding train data...
training the fast text model...
[]
Setting Configuration
Training the model
------------------------------
what's the problem behind this and what's how to solve it.
