### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by lishuaiCN** [BehroozMansouri/TangentCFT#18]
Hello @BehroozMansouri @ARQMath , this repo is very helpful, but when I ran **tangent_cft_combine_results.py** I got the error below:
Traceback (most recent call last):
  File "/workspace/formula1/TangentCFT/tangent_cft_module.py", line 115, in __get_vector_representation
    temp_vector = temp_vector + self.model.get_vector_representation(encoded_tuple)
  File "/workspace/formula1/TangentCFT/tangent_cft_model.py", line 44, in get_vector_representation
    return self.model.wv[encoded_math_tuple]
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 169, in __getitem__
    return self.get_vector(entities)
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 277, in get_vector
    return self.word_vec(word)
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1622, in word_vec
    raise KeyError('all ngrams for word %s absent from model' % word)
KeyError: 'all ngrams for word \x01⍸\x0fᆞ\x04 absent from model'
ERROR:root:'all ngrams for word \x01⍸\x0fᆞ\x04 absent from model'
Traceback (most recent call last):
  File "/workspace/formula1/TangentCFT/tangent_cft_module.py", line 115, in __get_vector_representation
    temp_vector = temp_vector + self.model.get_vector_representation(encoded_tuple)
  File "/workspace/formula1/TangentCFT/tangent_cft_model.py", line 44, in get_vector_representation
    return self.model.wv[encoded_math_tuple]
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 169, in __getitem__
    return self.get_vector(entities)
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 277, in get_vector
    return self.word_vec(word)
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1622, in word_vec
    raise KeyError('all ngrams for word %s absent from model' % word)
KeyError: 'all ngrams for word \x01⍸\x0fᆞ\x04 absent from model'
ERROR:root:'all ngrams for word ǣ҆\x01 absent from model'
Traceback (most recent call last):
  File "/workspace/formula1/TangentCFT/tangent_cft_module.py", line 115, in __get_vector_representation
    temp_vector = temp_vector + self.model.get_vector_representation(encoded_tuple)
  File "/workspace/formula1/TangentCFT/tangent_cft_model.py", line 44, in get_vector_representation
    return self.model.wv[encoded_math_tuple]
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 169, in __getitem__
    return self.get_vector(entities)
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 277, in get_vector
    return self.word_vec(word)
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1622, in word_vec
    raise KeyError('all ngrams for word %s absent from model' % word)
KeyError: 'all ngrams for word ǣ҆\x01 absent from model'
ERROR:root:'all ngrams for word ΈΈ\x07 absent from model'
Traceback (most recent call last):
  File "/workspace/formula1/TangentCFT/tangent_cft_module.py", line 115, in __get_vector_representation
    temp_vector = temp_vector + self.model.get_vector_representation(encoded_tuple)
  File "/workspace/formula1/TangentCFT/tangent_cft_model.py", line 44, in get_vector_representation
    return self.model.wv[encoded_math_tuple]
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 169, in __getitem__
    return self.get_vector(entities)
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 277, in get_vector
    return self.word_vec(word)
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1622, in word_vec
    raise KeyError('all ngrams for word %s absent from model' % word)
KeyError: 'all ngrams for word ΈΈ\x07 absent from model'
Traceback (most recent call last):
  File "tangent_cft_combine_results.py", line 100, in <module>
    main()
  File "tangent_cft_combine_results.py", line 80, in main
    tokenize_number=True)
  File "tangent_cft_combine_results.py", line 28, in get_vectors
    tokenize_all, tokenize_number)
  File "/workspace/formula1/TangentCFT/tangent_cft_back_end.py", line 81, in get_collection_query_vectors
    index_formula_id = self.module.index_collection_to_numpy(dictionary_formula_tuples_collection)
  File "/workspace/formula1/TangentCFT/tangent_cft_module.py", line 64, in index_collection_to_numpy
    vector = self.__get_vector_representation(dictionary_formula_lst_encoded_tuples[formula])
  File "/workspace/formula1/TangentCFT/tangent_cft_module.py", line 119, in __get_vector_representation
    return (temp_vector / counter)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

I have already ran slt, opt and slt_type command as  README guide, looking foward to your help, thank you!

**Comment by SmallBall8** [comment]
您好，和您遇到了同样的问题，请问您是怎么解决的呢？

**Comment by SmallBall8** [comment]
> 您好，和您遇到了同样的问题，请问您是怎么解决的呢？

@lishuaiCN

**Comment by lishuaiCN** [comment]
@SmallBall8 
有时候算法读取不到向量，所以除法“/”对Nonetype操作会报错，修改tangent_cft_module.py中的函数如如下，如果读不到向量认为赋0
    def index_collection_to_numpy(self, dictionary_formula_lst_encoded_tuples):
        """
        This methods takes in the dictionary of formula id and their corresponding list of tuples and returns a dictionary
        of formula id and their numpy vector representations
        """
        index_formula_id = {}
        for formula in dictionary_formula_lst_encoded_tuples:
            try:
                vector = self.__get_vector_representation(dictionary_formula_lst_encoded_tuples[formula])
            except:
                vector = numpy.zeros((1, 300),dtype="float32")
                continue
            vector = vector.reshape(1, 300)
            index_formula_id[formula] = vector
        return index_formula_id
